### ISSUE TITLE
Assignment submission to-do list

### ISSUE THREAD

**Issue by tpisel** [tpisel/flood-analysis#1]
**Completed Analysis Uploaded to GitHub (20 points)**

- [x] Updated README
- [x] Repo cleaned up

**Visualisations (20 points)**

- [x] 6-8 visualisations (2 per question)
- [x] Diagrams are labelled
- [x] Explanatory text

**Analysis and Conclusion (20 points)**

- [x] Summarise findings
- [x] Answer each question (with data, visualisations)
- [x] Employ statistical methods

**Group Presentation / Slides (40 points)**

- [x] Slides prepped
- [x] Talking points (for each person) prepped
